name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Avoid pre-populating the NuGet package cache

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all

      - name: Setup .NET 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.0.x

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Display SemVer
        run: |
            echo "SemVer: $GITVERSION_SEMVER"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore /p:Version=$GITVERSION_SEMVER

      - name: Test
        run: dotnet test --no-build --logger trx --logger console;verbosity=detailed --results-directory ../artifacts

      - name: Pack
        run: dotnet pack --no-build -c Release -o ../artifacts /p:Version=$GITVERSION_SEMVER

      - name: Upload NuGet packages as artifacts ⬆️
        uses: actions/upload-artifact@v3
        with:
          path: artifacts/dbup-redshift.$GITVERSION_SEMVER.nupkg

      - name: Test Report 🧪
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Tests
          path: artifacts/*.trx
          reporter: dotnet-trx
